$(document).ready(function () {
    var b = ("body")

    $('#fullpage').fullpage({
        navigation: true,
        afterLoad: function (origin, destination, direction) {
            var loadedSection = this;
            
            if ($(b).hasClass("fp-viewing-0")) {

                $('.nav').stop().animate({opacity: "0",})
                $('.wire').stop().animate({"bottom": "-1000px"})
                $('.front').stop().animate({"bottom": "-1000px"})
                $('.con10front').stop().animate({"bottom": "-1000px"})
                $('.w').stop().animate({ opacity: "0",})
                $('.con12phone-1').stop().animate({"left": "330px"})
                $('.banner').stop().animate({opacity:"0"})
                $('.line').stop().animate({"width":"0px"})
                $('.line2').stop().animate({"width":"0px"})
                $('.mains').stop().animate({opacity:"0"})
                $('.line3').stop().animate({"height":"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line3').stop().animate({ "height":"0px"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0px"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line5').stop().animate({"width":"0px"})
                $('.line6').stop().animate({"width":"0px"})
                $('.music').stop().animate({opacity:"0"})
                $('.dock').stop().animate({opacity:"0"})
                $('.con15left').stop().animate({opacity:"0"})
                $('.line7').stop().animate({"width":"0px"})
                $('.line8').stop().animate({"width":"0px"})
                $('.fllowing').stop().animate({opacity:"0"})
                $('.live').stop().animate({opacity:"0"})
                $('.lives').stop().animate({opacity:"0"})
                $('.line9').stop().animate({"width":"0px"})
                $('.line10').stop().animate({"width":"0px"})
                $('.on').stop().animate({opacity:"0"})
                $('.do').stop().animate({opacity:"0"})}

            //con1 

            if ($(b).hasClass("fp-viewing-1")) {

                $('.nav').stop().animate({opacity: "0",})
                $('.wire').stop().animate({"bottom": "-1000px"})
                $('.front').stop().animate({"bottom": "-1000px"})
                $('.con10front').stop().animate({"bottom": "-1000px"})
                $('.w').stop().animate({ opacity: "0",})
                $('.con12phone-1').stop().animate({"left": "330px"})
                $('.banner').stop().animate({opacity:"0"})
                $('.line').stop().animate({"width":"0px"})
                $('.line2').stop().animate({"width":"0px"})
                $('.mains').stop().animate({opacity:"0"})
                $('.line3').stop().animate({"height":"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line3').stop().animate({ "height":"0px"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0px"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line5').stop().animate({"width":"0px"})
                $('.line6').stop().animate({"width":"0px"})
                $('.music').stop().animate({opacity:"0"})
                $('.dock').stop().animate({opacity:"0"})
                $('.con15left').stop().animate({opacity:"0"})
                $('.line7').stop().animate({"width":"0px"})
                $('.line8').stop().animate({"width":"0px"})
                $('.fllowing').stop().animate({opacity:"0"})
                $('.live').stop().animate({opacity:"0"})
                $('.lives').stop().animate({opacity:"0"})
                $('.line9').stop().animate({"width":"0px"})
                $('.line10').stop().animate({"width":"0px"})
                $('.on').stop().animate({opacity:"0"})
                $('.do').stop().animate({opacity:"0"})}

            //con2

            if ($(b).hasClass("fp-viewing-2")) {
                
                $('.nav').stop().animate({opacity: "0",})
                $('.wire').stop().animate({"bottom": "-1000px"})
                $('.front').stop().animate({"bottom": "-1000px"})
                $('.con10front').stop().animate({"bottom": "-1000px"})
                $('.w').stop().animate({ opacity: "0",})
                $('.con12phone-1').stop().animate({"left": "330px"})
                $('.banner').stop().animate({opacity:"0"})
                $('.line').stop().animate({"width":"0px"})
                $('.line2').stop().animate({"width":"0px"})
                $('.mains').stop().animate({opacity:"0"})
                $('.line3').stop().animate({"height":"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line3').stop().animate({ "height":"0px"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0px"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line5').stop().animate({"width":"0px"})
                $('.line6').stop().animate({"width":"0px"})
                $('.music').stop().animate({opacity:"0"})
                $('.dock').stop().animate({opacity:"0"})
                $('.con15left').stop().animate({opacity:"0"})
                $('.line7').stop().animate({"width":"0px"})
                $('.line8').stop().animate({"width":"0px"})
                $('.fllowing').stop().animate({opacity:"0"})
                $('.live').stop().animate({opacity:"0"})
                $('.lives').stop().animate({opacity:"0"})
                $('.line9').stop().animate({"width":"0px"})
                $('.line10').stop().animate({"width":"0px"})
                $('.on').stop().animate({opacity:"0"})
                $('.do').stop().animate({opacity:"0"})}

            //con3

            if ($(b).hasClass("fp-viewing-3")) {

                $('.front').stop().animate({"bottom": "100px",},500)

                $('.nav').stop().animate({opacity: "0",})
                $('.wire').stop().animate({"bottom": "-1000px"})
                $('.con10front').stop().animate({"bottom": "-1000px"})
                $('.w').stop().animate({ opacity: "0",})
                $('.con12phone-1').stop().animate({"left": "330px"})
                $('.banner').stop().animate({opacity:"0"})
                $('.line').stop().animate({"width":"0px"})
                $('.line2').stop().animate({"width":"0px"})
                $('.mains').stop().animate({opacity:"0"})
                $('.line3').stop().animate({"height":"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line3').stop().animate({ "height":"0px"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0px"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line5').stop().animate({"width":"0px"})
                $('.line6').stop().animate({"width":"0px"})
                $('.music').stop().animate({opacity:"0"})
                $('.dock').stop().animate({opacity:"0"})
                $('.con15left').stop().animate({opacity:"0"})
                $('.line7').stop().animate({"width":"0px"})
                $('.line8').stop().animate({"width":"0px"})
                $('.fllowing').stop().animate({opacity:"0"})
                $('.live').stop().animate({opacity:"0"})
                $('.lives').stop().animate({opacity:"0"})
                $('.line9').stop().animate({"width":"0px"})
                $('.line10').stop().animate({"width":"0px"})
                $('.on').stop().animate({opacity:"0"})
                $('.do').stop().animate({opacity:"0"})}

            //con4

            if ($(b).hasClass("fp-viewing-4")) {

                $('.wire').stop().animate({"bottom": "0px",},500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            // con5

            if ($(b).hasClass("fp-viewing-5")) {

                $('.nav').stop().animate({opacity: "1",},500)
                $('.box').stop().animate({"top":"-10px"},500)    

                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            // con6

            if ($(b).hasClass("fp-viewing-6")) {

                $('.nav').stop().animate({opacity: "1",},500)
                $('.box').stop().animate({ "top":"120px"},500)

                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            // con7
            if ($(b).hasClass("fp-viewing-7")) {

                $('.nav').stop().animate({opacity: "1",}, 500)
                $('.box').stop().animate({ "top":"250px"},500)

                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            // con8

            if ($(b).hasClass("fp-viewing-8")) {

                $('.nav').stop().animate({opacity: "0",})
                $('.wire').stop().animate({"bottom": "-1000px"})
                $('.front').stop().animate({"bottom": "-1000px"})
                $('.con10front').stop().animate({"bottom": "-1000px"})
                $('.w').stop().animate({ opacity: "0",})
                $('.con12phone-1').stop().animate({"left": "330px"})
                $('.line').stop().animate({"width":"0px"})
                $('.banner').stop().animate({opacity:"0"})
                $('.line2').stop().animate({"width":"0px"})
                $('.mains').stop().animate({opacity:"0"})
                $('.line3').stop().animate({"height":"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0px"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line5').stop().animate({"width":"0px"})
                $('.line6').stop().animate({"width":"0px"})
                $('.music').stop().animate({opacity:"0"})
                $('.dock').stop().animate({opacity:"0"})
                $('.con15left').stop().animate({opacity:"0"})
                $('.line7').stop().animate({"width":"0px"})
                $('.line8').stop().animate({"width":"0px"})
                $('.fllowing').stop().animate({opacity:"0"})
                $('.live').stop().animate({opacity:"0"})
                $('.lives').stop().animate({opacity:"0"})
                $('.line9').stop().animate({"width":"0px"})
                $('.line10').stop().animate({"width":"0px"})
                $('.on').stop().animate({opacity:"0"})
                $('.do').stop().animate({opacity:"0"})}

            // con9

            if ($(b).hasClass("fp-viewing-9")) {

                $('.con10front').stop().animate({"bottom": "70px",}, 500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            // con10
            if ($(b).hasClass("fp-viewing-10")) {

                $('.w').stop().animate({ opacity: "1",}, 500)

                $('.nav').stop().animate({opacity: "0",})
                $('.wire').stop().animate({"bottom": "-1000px"})
                $('.front').stop().animate({"bottom": "-1000px"})
                $('.con10front').stop().animate({"bottom": "-1000px"})
                $('.con12phone-1').stop().animate({"left": "330px"})
                $('.line').stop().animate({"width":"0px"})
                $('.banner').stop().animate({opacity:"0"})
                $('.line2').stop().animate({"width":"0px"})
                $('.mains').stop().animate({opacity:"0"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line3').stop().animate({ "height":"0px"})
                $('.search').stop().animate({opacity:"0"})
                $('.album').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line4').stop().animate({"width":"0px"})
                $('.con14album').stop().animate({opacity:"0"})
                $('.zoomin').stop().animate({opacity:"0"})
                $('.line5').stop().animate({"width":"0px"})
                $('.line6').stop().animate({"width":"0px"})
                $('.music').stop().animate({opacity:"0"})
                $('.dock').stop().animate({opacity:"0"})
                $('.con15left').stop().animate({opacity:"0"})
                $('.line7').stop().animate({"width":"0px"})
                $('.line8').stop().animate({"width":"0px"})
                $('.fllowing').stop().animate({opacity:"0"})
                $('.live').stop().animate({opacity:"0"})
                $('.lives').stop().animate({opacity:"0"})
                $('.line9').stop().animate({"width":"0px"})
                $('.line10').stop().animate({"width":"0px"})
                $('.on').stop().animate({opacity:"0"})
                $('.do').stop().animate({opacity:"0"})}

            // con11

            if ($(b).hasClass("fp-viewing-11")) {

                $('.con12phone-1').stop().animate({"left": "530px",}, 500)
                $('.line').stop().delay(500).animate({"width":"300px"},500)
                $('.banner').stop().delay(1000).animate({opacity:"1"},500)
                $('.line2').stop().delay(1500).animate({"width":"300px"},500)
                $('.mains').stop().delay(2000).animate({opacity:"1"},500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            // con12
            if ($(b).hasClass("fp-viewing-12")) {

                $('.line3').stop().animate({"height":"360px"},500)
                $('.search').stop().delay(500).animate({opacity:"1"},500)
                $('.album').stop().delay(1000).animate({opacity:"1"},500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            //con13

            if ($(b).hasClass("fp-viewing-13")) {
                $('.line4').stop().animate({"width":"300px"},500)
                $('.con14album').stop().delay(500).animate({opacity:"1"},500)
                $('.zoomin').stop().delay(1000).animate({opacity:"1"},500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}
                
            //con14

            if ($(b).hasClass("fp-viewing-14")) {
                $('.line5').stop().animate({"width":"300px"},500)
                $('.line6').stop().delay(1500).animate({"width":"300px"},500)
                $('.music').stop().delay(500).animate({opacity:"1"},500)
                $('.dock').stop().delay(2000).animate({opacity:"1"},500)
                $('.con15left').stop().delay(1000).animate({opacity:"1"},500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})}
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})

            // con15

            if ($(b).hasClass("fp-viewing-15")) {

                $('.line7').stop().animate({"width":"390px"},500)
                $('.line8').stop().delay(1000).animate({"width":"410px"},500)
                $('.fllowing').stop().delay(500).animate({opacity:"1"},500)
                $('.live').stop().delay(1500).animate({opacity:"1"},500)
                $('.lives').stop().delay(2000).animate({opacity:"1"},500)



                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line9').stop().animate({"width":"0px"})
                    $('.line10').stop().animate({"width":"0px"})
                    $('.on').stop().animate({opacity:"0"})
                    $('.do').stop().animate({opacity:"0"})}

            //con16

            if ($(b).hasClass("fp-viewing-16")) {
                $('.line9').stop().animate({"width":"400px"},500)
                $('.line10').stop().delay(1000).animate({"width":"400px"},500)
                $('.on').stop().delay(500).animate({opacity:"1"},500)
                $('.do').stop().delay(1500).animate({opacity:"1"},500)

                    $('.nav').stop().animate({opacity: "0",})
                    $('.wire').stop().animate({"bottom": "-1000px"})
                    $('.front').stop().animate({"bottom": "-1000px"})
                    $('.con10front').stop().animate({"bottom": "-1000px"})
                    $('.w').stop().animate({ opacity: "0",})
                    $('.con12phone-1').stop().animate({"left": "330px"})
                    $('.banner').stop().animate({opacity:"0"})
                    $('.line').stop().animate({"width":"0px"})
                    $('.line2').stop().animate({"width":"0px"})
                    $('.mains').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({"height":"0"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line3').stop().animate({ "height":"0px"})
                    $('.search').stop().animate({opacity:"0"})
                    $('.album').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line4').stop().animate({"width":"0px"})
                    $('.con14album').stop().animate({opacity:"0"})
                    $('.zoomin').stop().animate({opacity:"0"})
                    $('.line5').stop().animate({"width":"0px"})
                    $('.line6').stop().animate({"width":"0px"})
                    $('.music').stop().animate({opacity:"0"})
                    $('.dock').stop().animate({opacity:"0"})
                    $('.con15left').stop().animate({opacity:"0"})
                    $('.line7').stop().animate({"width":"0px"})
                    $('.line8').stop().animate({"width":"0px"})
                    $('.fllowing').stop().animate({opacity:"0"})
                    $('.live').stop().animate({opacity:"0"})
                    $('.lives').stop().animate({opacity:"0"})}
        
    }
    })
})